export const utilities = [
  {
    name: 'Electricity',
    note: 'Power supply for the property',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Electricity.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Water',
    note: 'Hot and cold water supply',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Water.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Internet',
    note: 'High-speed internet access',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Internet.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Gas',
    note: 'Natural gas supply',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Gas.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Trash Collection',
    note: 'Regular garbage pickup',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Trash_Collection.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Heating',
    note: 'Central heating system',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Heating.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Cable TV',
    note: 'Cable television service',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Cable_TV.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Landscaping',
    note: 'Maintenance of outdoor spaces',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Landscaping.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Security',
    note: 'Security services and systems',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Security.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Fitness Center',
    note: 'On-site gym facilities',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Fitness_Center.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Swimming Pool',
    note: 'Community swimming pool',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Swimming_Pool.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Parking',
    note: 'Reserved parking spaces',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Parking.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Laundry Facilities',
    note: 'On-site laundry facilities',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Laundry_Facilities.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Dishwasher',
    note: 'In-unit dishwasher',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Dishwasher.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Microwave',
    note: 'Kitchen microwave',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Microwave.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Refrigerator',
    note: 'Apartment refrigerator',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Refrigerator.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Oven',
    note: 'Oven for cooking',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Oven.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Air Conditioning',
    note: 'Climate control system',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Air_Conditioning.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Fireplace',
    note: 'Indoor fireplace',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Fireplace.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Balcony',
    note: 'Private balcony space',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Balcony.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Pet-Friendly',
    note: 'Pet-friendly policy',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Pet_Friendly.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: '24/7 Maintenance',
    note: 'Round-the-clock maintenance service',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/247_Maintenance.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Garage',
    note: 'Covered parking garage',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Garage.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Roof Deck',
    note: 'Rooftop deck with views',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Roof_Deck.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Package Receiving',
    note: 'Package delivery services',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Package_Receiving.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Barbecue Area',
    note: 'Outdoor barbecue and picnic area',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Barbecue_Area.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Wheelchair Accessible',
    note: 'Accessibility features',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Wheelchair_Accessible.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Bike Storage',
    note: 'Bicycle storage facilities',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Bike_Storage.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Elevator',
    note: 'Elevator access to units',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Elevator.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Pet Park',
    note: 'Outdoor pet exercise area',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Pet_Park.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Playground',
    note: "Children's playground",
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Playground.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Storage Space',
    note: 'Additional storage options',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Storage_Space.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Concierge Service',
    note: 'Concierge and support services',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Concierge_Service.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Dining Area',
    note: 'Dedicated dining spaces',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Dining_Area.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Game Room',
    note: 'Recreational game room',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Game_Room.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Garbage Collection',
    note: 'Regular waste collection services',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Garbage_Collection.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Pest Control',
    note: 'Professional pest control services',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Pest_Control.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Electric Car Charging',
    note: 'Charging stations for electric cars',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Electric_Car_Charging.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Car Wash Station',
    note: 'Convenient car washing facilities',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Car_Wash_Station.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Parcel Lockers',
    note: 'Secure parcel delivery lockers',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Parcel_Lockers.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Yoga Studio',
    note: 'Dedicated yoga and fitness studio',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Yoga_Studio.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Recycling Center',
    note: 'On-site recycling facilities',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Recycling_Center.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Guest Parking',
    note: 'Parking for visitors and guests',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Guest_Parking.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Computer Lab',
    note: 'Computer and tech lab',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Computer_Lab.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Billiards Room',
    note: 'Billiards and game room',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Billiards_Room.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Dry Cleaning Service',
    note: 'Convenient dry cleaning services',
    icon: 'https://image-user-public.s3.ap-southeast-2.amazonaws.com/utilities/Dry_Cleaning_Service.png',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
