export const utilities = [
  {
    name: 'Electricity',
    note: 'Power supply for the property',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Water',
    note: 'Hot and cold water supply',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Internet',
    note: 'High-speed internet access',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Gas',
    note: 'Natural gas supply',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Trash Collection',
    note: 'Regular garbage pickup',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Heating',
    note: 'Central heating system',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Cable TV',
    note: 'Cable television service',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Sewer',
    note: 'Sewage system and maintenance',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Waste Disposal',
    note: 'Garbage and waste disposal service',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Landscaping',
    note: 'Maintenance of outdoor spaces',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Snow Removal',
    note: 'Snow clearing in winter',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Security',
    note: 'Security services and systems',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Fitness Center',
    note: 'On-site gym facilities',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Swimming Pool',
    note: 'Community swimming pool',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Parking',
    note: 'Reserved parking spaces',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Laundry Facilities',
    note: 'On-site laundry facilities',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Dishwasher',
    note: 'In-unit dishwasher',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Microwave',
    note: 'Kitchen microwave',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Refrigerator',
    note: 'Apartment refrigerator',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Oven',
    note: 'Oven for cooking',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Air Conditioning',
    note: 'Climate control system',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Fireplace',
    note: 'Indoor fireplace',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Balcony',
    note: 'Private balcony space',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Pet-Friendly',
    note: 'Pet-friendly policy',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: '24/7 Maintenance',
    note: 'Round-the-clock maintenance service',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Garage',
    note: 'Covered parking garage',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Roof Deck',
    note: 'Rooftop deck with views',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Package Receiving',
    note: 'Package delivery services',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'On-Site Management',
    note: 'On-site property management',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Barbecue Area',
    note: 'Outdoor barbecue and picnic area',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Wheelchair Accessible',
    note: 'Accessibility features',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Bike Storage',
    note: 'Bicycle storage facilities',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Lounge',
    note: 'Community lounge and common areas',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Elevator',
    note: 'Elevator access to units',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Conference Room',
    note: 'Meeting and conference room',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Library',
    note: 'On-site library or reading area',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Courtyard',
    note: 'Outdoor courtyard space',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Tennis Court',
    note: 'On-site tennis court',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Golf Course',
    note: 'Nearby golf course access',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Pet Park',
    note: 'Outdoor pet exercise area',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Playground',
    note: "Children's playground",
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Guest Parking',
    note: 'Parking for guests',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Storage Space',
    note: 'Additional storage options',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Concierge Service',
    note: 'Concierge and support services',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Dining Area',
    note: 'Dedicated dining spaces',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Game Room',
    note: 'Recreational game room',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Library',
    note: 'On-site library or reading area',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Gardening Area',
    note: 'Community gardening area',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Garbage Collection',
    note: 'Regular waste collection services',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'HVAC System',
    note: 'Heating, ventilation, and air conditioning',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Pest Control',
    note: 'Professional pest control services',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Dedicated Storage',
    note: 'Additional storage units available',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Guest Suites',
    note: 'Guest accommodation options',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Rooftop Garden',
    note: 'Garden on the rooftop',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Outdoor Pool',
    note: 'Outdoor swimming pool',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Pet Grooming Station',
    note: 'On-site pet grooming area',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Media Room',
    note: 'Dedicated media and movie room',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Dog Park',
    note: 'Fenced dog exercise area',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Electric Car Charging',
    note: 'Charging stations for electric cars',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Car Wash Station',
    note: 'Convenient car washing facilities',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Community Events',
    note: 'Organized community events',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Bike Repair Station',
    note: 'Station for bicycle repairs',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Coffee Bar',
    note: 'On-site coffee and refreshment bar',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Parcel Lockers',
    note: 'Secure parcel delivery lockers',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Yoga Studio',
    note: 'Dedicated yoga and fitness studio',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Recycling Center',
    note: 'On-site recycling facilities',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Guest Parking',
    note: 'Parking for visitors and guests',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Gated Community',
    note: 'Security with gated access',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Playroom',
    note: "Children's playroom",
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Computer Lab',
    note: 'Computer and tech lab',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Billiards Room',
    note: 'Billiards and game room',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Tanning Beds',
    note: 'Indoor tanning facilities',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Basketball Court',
    note: 'On-site basketball court',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Community Kitchen',
    note: 'Community kitchen space',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Tennis Court',
    note: 'On-site tennis court',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Mailroom',
    note: 'Mail and package receiving area',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Dry Cleaning Service',
    note: 'Convenient dry cleaning services',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Study Lounge',
    note: 'Quiet study and reading lounge',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Party Room',
    note: 'Party and event room',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Concierge Desk',
    note: 'Front desk concierge service',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Zen Garden',
    note: 'Tranquil Zen garden',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Walking Trails',
    note: 'Scenic walking and nature trails',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Racquetball Court',
    note: 'Indoor racquetball court',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Movie Theater',
    note: 'Private movie screening theater',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Ski Storage',
    note: 'Storage for skiing equipment',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Art Studio',
    note: 'Creative art studio',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Car Charging Stations',
    note: 'Electric vehicle charging',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Aquarium',
    note: 'In-house aquarium display',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Wine Cellar',
    note: 'Private wine storage',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Music Room',
    note: 'Soundproof music practice rooms',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Bowling Alley',
    note: 'On-site bowling alley',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Fire Pit',
    note: 'Outdoor fire pit and seating',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Fountain',
    note: 'Decorative outdoor fountains',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Dance Studio',
    note: 'Dedicated dance and exercise studio',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Community Garden',
    note: 'Community gardening spaces',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Roof Terrace',
    note: 'Terrace with city views',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Juice Bar',
    note: 'On-site juice and smoothie bar',
    created_id: 4,
    updated_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
